import { NextResponse } from "next/server";
import { getAllProviders, getLastUpdated } from "@/lib/data";
import type { Model, Provider } from "@/lib/types";

// Static route (llmstxt.org spec, full companion doc) — prerendered at build,
// refreshed on the nightly rebuild (data/providers.json is regenerated by
// scripts/sync.mjs). Machine-readable dump of every provider + model.
export const dynamic = "force-static";

function fmtDate(iso: string | null): string {
  if (!iso) return "-";
  return iso.slice(0, 10);
}

function escapeCell(v: string): string {
  return v.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

// Model identity column ("Model") is always shown; the rest are omitted
// entirely for a provider if NONE of its models have that field (anti-
// hallucination: no column of all-empty cells).
function modelsTable(models: Model[]): string[] {
  if (models.length === 0) return [];

  const optionalCols: { key: keyof Model; label: string }[] = [
    { key: "context", label: "Context" },
    { key: "maxOutput", label: "Max Output" },
    { key: "modality", label: "Modality" },
    { key: "rateLimit", label: "Rate Limit" },
  ];
  const activeCols = optionalCols.filter((c) => models.some((m) => m[c.key]));
  const headers = ["Model", ...activeCols.map((c) => c.label)];

  const lines: string[] = [];
  lines.push(`| ${headers.join(" | ")} |`);
  lines.push(`| ${headers.map(() => "---").join(" | ")} |`);
  for (const m of models) {
    const row = [
      escapeCell(m.name),
      ...activeCols.map((c) => escapeCell(m[c.key] ?? "-")),
    ];
    lines.push(`| ${row.join(" | ")} |`);
  }
  return lines;
}

function providerSection(p: Provider): string[] {
  const lines: string[] = [];

  lines.push(`## ${p.name}`);
  lines.push("");

  if (p.url) lines.push(`URL: ${p.url}`);
  if (p.baseUrl) lines.push(`Base URL: ${p.baseUrl}`);
  if (p.url || p.baseUrl) lines.push("");

  if (p.description) {
    lines.push(p.description);
    lines.push("");
  }

  if (p.modalities.length > 0) {
    lines.push(`Modalitas: ${p.modalities.join(", ")}`);
    lines.push("");
  }

  if (p.freeLimit) {
    lines.push(`Gratis: ${p.freeLimit}`);
    lines.push("");
  }

  const table = modelsTable(p.models);
  if (table.length > 0) {
    lines.push(...table);
    lines.push("");
  }

  if (p.moreModels) {
    lines.push(p.moreModels);
    lines.push("");
  }

  lines.push("Sumber:");
  for (const s of p.sources) {
    lines.push(`- ${s.name} (${s.url}) — synced ${fmtDate(s.syncedAt)}`);
  }
  lines.push("");

  return lines;
}

export function GET() {
  const providers = getAllProviders();
  const lastUpdated = fmtDate(getLastUpdated());

  const lines: string[] = [];

  lines.push("# tokengratis.id — data lengkap (llms-full.txt)");
  lines.push("");
  lines.push(
    '> Direktori free tier & free credits API LLM, di-aggregate otomatis dari sumber komunitas Indonesia. Aggregator, bukan verifier — tidak ada klaim "verified" di mana pun.'
  );
  lines.push("");
  lines.push(`Terakhir di-update: ${lastUpdated}.`);
  lines.push(
    "Field yang tidak muncul di sebuah entri berarti sumber datanya memang tidak menyediakan info itu secara terstruktur — bukan ditebak, bukan dikosongkan paksa jadi placeholder."
  );
  lines.push("");

  for (const p of providers) {
    lines.push(...providerSection(p));
  }

  return new NextResponse(lines.join("\n"), {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
