import { NextResponse } from "next/server";
import { getAllProviders } from "@/lib/data";

// Static route — prerendered at build, refreshed on the nightly rebuild
// (data/providers.json is regenerated by scripts/sync.mjs). Public JSON API:
// bare array (no envelope) so other builders — MCP servers, CLIs — can
// consume it directly.
export const dynamic = "force-static";

export function GET() {
  const providers = getAllProviders();

  return NextResponse.json(providers, {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
