import { NextResponse } from "next/server";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Static route (RSS 2.0) — prerendered at build, refreshed on the nightly
// rebuild (data/changelog.json is regenerated by scripts/sync.mjs alongside
// data/providers.json). Reader lokal biar file ini ga gantung ke lib/data.ts
// (dipegang agent lain) — sama pola dengan app/changelog/page.tsx.
export const dynamic = "force-static";

const BASE = "https://tokengratis.id";

interface ChangelogProviderRef {
  slug: string;
  name: string;
}

interface ChangelogModelDiff {
  provider: string;
  added: string[];
  removed: string[];
}

interface ChangelogEntry {
  date: string; // YYYY-MM-DD
  providersAdded: ChangelogProviderRef[];
  providersRemoved: ChangelogProviderRef[];
  models: ChangelogModelDiff[];
}

function getChangelog(): ChangelogEntry[] {
  try {
    const raw = readFileSync(join(process.cwd(), "data", "changelog.json"), "utf8");
    const parsed = JSON.parse(raw);
    if (!Array.isArray(parsed)) return [];
    return [...parsed].sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  } catch {
    return [];
  }
}

/** XML-escape apapun yang di-interpolate — nama provider/model bisa
 * mengandung `&`, `<`, `>`, kutip, dst yang bakal bikin XML invalid. */
function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** RFC-822 date buat <pubDate> — pakai jam 00:00 UTC (changelog cuma
 * nyimpen tanggal, bukan jam). */
function toRfc822(date: string): string {
  try {
    return new Date(`${date}T00:00:00Z`).toUTCString();
  } catch {
    return new Date(0).toUTCString();
  }
}

function entryTitle(entry: ChangelogEntry): string {
  const parts: string[] = [];

  const modelAdds = entry.models.reduce((sum, m) => sum + m.added.length, 0);
  const modelRemoves = entry.models.reduce((sum, m) => sum + m.removed.length, 0);

  if (modelAdds > 0) parts.push(`${modelAdds} model baru`);
  if (entry.providersAdded.length > 0) {
    parts.push(
      `${entry.providersAdded.length} provider baru`,
    );
  }
  if (modelRemoves > 0) parts.push(`${modelRemoves} model hilang`);
  if (entry.providersRemoved.length > 0) {
    parts.push(`${entry.providersRemoved.length} provider hilang`);
  }

  if (parts.length === 0) return `Perubahan data ${entry.date}`;
  return parts.join(", ");
}

function entryDescription(entry: ChangelogEntry): string {
  const lines: string[] = [];

  for (const p of entry.providersAdded) lines.push(`Provider baru: ${p.name}`);
  for (const p of entry.providersRemoved) lines.push(`Provider dihapus: ${p.name}`);
  for (const m of entry.models) {
    for (const name of m.added) lines.push(`+ ${name} di ${m.provider}`);
    for (const name of m.removed) lines.push(`− ${name} dari ${m.provider}`);
  }

  if (lines.length === 0) return "Tidak ada perubahan tercatat.";
  return lines.join("; ");
}

function itemXml(entry: ChangelogEntry): string {
  const title = escapeXml(entryTitle(entry));
  const description = escapeXml(entryDescription(entry));
  const link = `${BASE}/changelog`;
  const guid = `${BASE}/changelog#${entry.date}`;
  const pubDate = toRfc822(entry.date);

  return [
    "    <item>",
    `      <title>${title}</title>`,
    `      <link>${escapeXml(link)}</link>`,
    `      <guid isPermaLink="false">${escapeXml(guid)}</guid>`,
    `      <pubDate>${pubDate}</pubDate>`,
    `      <description>${description}</description>`,
    "    </item>",
  ].join("\n");
}

function buildFeed(entries: ChangelogEntry[]): string {
  const now = new Date().toUTCString();
  const items = entries.map(itemXml).join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">',
    "  <channel>",
    `    <title>${escapeXml("tokengratis.id — Perubahan Data")}</title>`,
    `    <link>${escapeXml(BASE)}</link>`,
    `    <description>${escapeXml(
      "Riwayat perubahan data tokengratis.id: model & provider baru, model yang hilang — di-generate otomatis tiap malam dari hasil sync. Aggregator transparan, bukan verifier.",
    )}</description>`,
    "    <language>id-ID</language>",
    `    <lastBuildDate>${now}</lastBuildDate>`,
    `    <atom:link href="${escapeXml(`${BASE}/feed.xml`)}" rel="self" type="application/rss+xml" />`,
    items,
    "  </channel>",
    "</rss>",
  ]
    .filter(Boolean)
    .join("\n");
}

export function GET() {
  // On any read/parse failure, getChangelog() already returns [] rather
  // than throwing — a 500 on a feed URL is worse than an empty feed.
  const entries = getChangelog();
  const xml = buildFeed(entries);

  return new NextResponse(xml, {
    headers: { "Content-Type": "application/rss+xml; charset=utf-8" },
  });
}
