import { NextResponse } from "next/server";
import { getAllProviders } from "@/lib/data";

// Static route — prerendered at build, refreshed on the nightly rebuild
// (data/providers.json is regenerated by scripts/sync.mjs). Flattened model
// list (one entry per model across all providers) as a bare JSON array.
export const dynamic = "force-static";

interface FlatModel {
  providerSlug: string;
  providerName: string;
  id: string;
  name: string;
  context: string | null;
  maxOutput: string | null;
  modality: string | null;
  rateLimit: string | null;
}

export function GET() {
  const providers = getAllProviders();

  const models: FlatModel[] = providers.flatMap((p) =>
    p.models.map((m) => ({
      providerSlug: p.slug,
      providerName: p.name,
      id: m.id,
      name: m.name,
      context: m.context,
      maxOutput: m.maxOutput,
      modality: m.modality,
      rateLimit: m.rateLimit,
    })),
  );

  return NextResponse.json(models, {
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Access-Control-Allow-Origin": "*",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
