import { NextResponse } from "next/server";
import { getAllProviders, getLastUpdated } from "@/lib/data";

// Static route (llmstxt.org spec) — prerendered at build, refreshed on the
// nightly rebuild (data/providers.json is regenerated by scripts/sync.mjs).
export const dynamic = "force-static";

const BASE = "https://tokengratis.id";

function fmtDate(iso: string | null): string {
  if (!iso) return "-";
  return iso.slice(0, 10);
}

export function GET() {
  const providers = getAllProviders();
  const lastUpdated = fmtDate(getLastUpdated());

  const lines: string[] = [];

  lines.push("# tokengratis.id");
  lines.push("");
  lines.push(
    "> Direktori free tier & free credits API LLM, di-aggregate otomatis dari sumber komunitas Indonesia. Aggregator, bukan verifier."
  );
  lines.push("");
  lines.push(
    `Data di situs ini di-generate otomatis dari beberapa sumber komunitas publik (atribusi lengkap per-provider ada di tiap halaman detail), terakhir di-sync ${lastUpdated}. Tidak ada klaim "verified" — tiap entri cuma menampilkan dari mana datanya berasal dan kapan di-sync. Field yang tidak ada di sumber tidak ditampilkan (bukan ditebak).`
  );
  lines.push("");
  lines.push("## Halaman");
  lines.push("");
  lines.push(`- [Beranda](${BASE}): daftar lengkap provider API LLM gratis.`);
  lines.push(
    `- [Proyek Open Source](${BASE}/opensource): direktori proyek open-source buatan developer Indonesia.`
  );

  for (const p of providers) {
    const bits: string[] = [`${p.modelCount} model`];
    if (p.maxContext) bits.push(`context maks ${p.maxContext}`);
    lines.push(`- [${p.name}](${BASE}/provider/${p.slug}): ${bits.join(", ")}.`);
  }

  lines.push("");
  lines.push("## Data lengkap");
  lines.push("");
  lines.push(
    `- [llms-full.txt](${BASE}/llms-full.txt): dump lengkap semua provider + model (deskripsi, modalitas, tabel model, sumber) dalam markdown, buat konsumsi LLM/agent.`
  );
  lines.push("");

  return new NextResponse(lines.join("\n"), {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
